export type HealthItem = {
  name: string;
  unit: string;
  values: (string | null)[];
  reference: string;
};

export type HealthCategory = {
  name: string;
  items: HealthItem[];
};

// Imported from the owner's ‘Полная матрица’ spreadsheet.
export const dates = ["03.01.2021","10.01.2021","18.08.2021","25.08.2021","27.08.2021","01.08.2022","03.08.2022","06.03.2024","07.03.2024","08.03.2024","09.03.2024","12.07.2024","17.07.2024","27.09.2025","05.01.2026","09.07.2026","07.08.2026","15.08.2026"] as const;

export const healthCategories: HealthCategory[] = [
  { name: "Общий анализ мочи", items: [
    { name: "Цвет", unit: "", values: ["Жёлтый",null,null,null,null,"Светло-жёлтый",null,"Светло-жёлтый",null,null,null,null,null,null,"Светло-жёлтый",null,null,null], reference: "03.01.2021, 01.08.2022: от светло-жёлтого до жёлтого\n05.01.2026: Светло-жёлтый" },
    { name: "Удельный вес", unit: "", values: ["1.025",null,null,null,null,"1.03",null,"1.025","1.025",null,null,null,null,null,"1.018",null,null,null], reference: "03.01.2021, 01.08.2022: 1.010-1.035\n05.01.2026: 1.005-1.030" },
    { name: "pH", unit: "", values: ["6",null,null,null,null,"6",null,"5.5",null,null,null,null,null,null,"5.5",null,null,null], reference: "03.01.2021, 01.08.2022: 4.6-8.0\n05.01.2026: 5.5-7.0" },
    { name: "Белок", unit: "г/л", values: ["0.096",null,null,null,null,"0.072",null,"Отрицательно","Отрицательно",null,null,null,null,null,"Отрицательно",null,null,null], reference: "03.01.2021, 01.08.2022: 0-0.12\n05.01.2026: Отрицательно" },
    { name: "Глюкоза", unit: "", values: ["Отрицательно",null,null,null,null,"Отрицательно",null,"Отрицательно",null,null,null,null,null,null,"Отрицательно",null,null,null], reference: "Отрицательно" },
    { name: "Кетоновые тела", unit: "", values: ["Отрицательно",null,null,null,null,"Отрицательно",null,"5 мг/дл",null,null,null,null,null,null,"Отрицательно",null,null,null], reference: "Отрицательно" },
    { name: "Нитриты", unit: "", values: ["Положительно",null,null,null,null,"Отрицательно",null,"Отрицательно",null,null,null,null,null,null,"Отрицательно",null,null,null], reference: "Отрицательно" },
    { name: "Билирубин", unit: "", values: ["Отрицательно",null,null,null,null,"Отрицательно",null,"Отрицательно",null,null,null,null,null,null,"Отрицательно",null,null,null], reference: "Отрицательно" },
    { name: "Уробилиноген", unit: "мг/дл", values: ["0.2",null,null,null,null,"0.2",null,"0.2",null,null,null,null,null,null,"0.2",null,null,null], reference: "03.01.2021, 01.08.2022: до 2.0\n05.01.2026: до 1.0" },
    { name: "Переходный эпителий", unit: "в п/зр", values: ["Не обнаружен",null,null,null,null,"Не обнаружен",null,"0",null,null,null,null,null,null,"0",null,null,null], reference: "03.01.2021, 01.08.2022: Не обнаружен\n05.01.2026: 0-1" },
    { name: "Плоский эпителий", unit: "в п/зр", values: ["0-0-1",null,null,null,null,"1-2-2",null,"0",null,null,null,null,null,null,"0",null,null,null], reference: "03.01.2021, 01.08.2022: до 5\n05.01.2026: 0-5" },
    { name: "Лейкоциты", unit: "в п/зр", values: ["2-2-3",null,null,null,null,"2-3-4",null,"1",null,null,null,null,null,null,"1",null,null,null], reference: "03.01.2021, 01.08.2022: до 3\n05.01.2026: 0-5" },
    { name: "Эритроциты неизменённые", unit: "в п/зр", values: ["0-0-1",null,null,null,null,"Не обнаружены",null,null,null,null,null,null,null,null,null,null,null,null], reference: "Не обнаружены" },
    { name: "Эритроциты изменённые", unit: "в п/зр", values: ["Не обнаружены",null,null,null,null,"Не обнаружены",null,null,null,null,null,null,null,null,null,null,null,null], reference: "Не обнаружены" },
    { name: "Цилиндры", unit: "в п/зр", values: ["Гиалиновые 0-0-1",null,null,null,null,"Не обнаружены",null,null,null,null,null,null,null,null,null,null,null,null], reference: "Не обнаружены" },
    { name: "Клетки почечного эпителия", unit: "в п/зр", values: ["Не обнаружены",null,null,null,null,"Не обнаружены",null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "03.01.2021, 01.08.2022: Не обнаружены\n05.01.2026: 0" },
    { name: "Соли", unit: "", values: ["Не обнаружены",null,null,null,null,"Не обнаружены",null,null,null,null,null,null,null,null,null,null,null,null], reference: "Не обнаружены" },
    { name: "Слизь", unit: "", values: ["+",null,null,null,null,"++",null,"++",null,null,null,null,null,null,"++",null,null,null], reference: "до +" },
    { name: "Бактерии", unit: "", values: ["+",null,null,null,null,"+",null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "03.01.2021, 01.08.2022: Не обнаружены\n05.01.2026: до +" },
    { name: "Прозрачность", unit: "", values: [null,null,null,null,null,null,null,"Прозрачная",null,null,null,null,null,null,"Прозрачная",null,null,null], reference: "Прозрачная" },
    { name: "Эритроциты", unit: "в п/зр", values: [null,null,null,null,null,null,null,"2",null,null,null,null,null,null,"0",null,null,null], reference: "0-3" },
    { name: "Цилиндры гиалиновые", unit: "в п/зр", values: [null,null,null,null,null,null,null,"0",null,null,null,null,null,null,"0",null,null,null], reference: "0" },
    { name: "Цилиндры зернистые", unit: "в п/зр", values: [null,null,null,null,null,null,null,"0",null,null,null,null,null,null,"0",null,null,null], reference: "0" },
    { name: "Аморфные соли", unit: "", values: [null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
    { name: "Оксалаты", unit: "", values: [null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
    { name: "Трипельфосфаты", unit: "", values: [null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
    { name: "Кристаллы мочевой кислоты", unit: "", values: [null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
  ] },
  { name: "УЗИ мочевого пузыря, почек и простаты", items: [
    { name: "Объём мочевого пузыря", unit: "мл", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"330",null,null,null], reference: "" },
    { name: "Толщина стенки мочевого пузыря", unit: "мм", values: [null,"3",null,null,null,null,null,null,null,null,null,null,null,null,"4",null,null,null], reference: "" },
    { name: "Правая почка: длина", unit: "мм", values: [null,"104",null,null,null,null,"112",null,null,null,null,null,null,null,"122",null,null,null], reference: "" },
    { name: "Правая почка: ширина", unit: "мм", values: [null,"50",null,null,null,null,"52",null,null,null,null,null,null,null,"46",null,null,null], reference: "" },
    { name: "Левая почка: длина", unit: "мм", values: [null,"109",null,null,null,null,"113",null,null,null,null,null,null,null,"114",null,null,null], reference: "" },
    { name: "Левая почка: ширина", unit: "мм", values: [null,"48",null,null,null,null,"51",null,null,null,null,null,null,null,"49",null,null,null], reference: "" },
    { name: "Паренхима правой почки", unit: "мм", values: [null,"16",null,null,null,null,"16",null,null,null,null,null,null,null,"17",null,null,null], reference: "" },
    { name: "Паренхима левой почки", unit: "мм", values: [null,"16",null,null,null,null,"16",null,null,null,null,null,null,null,"17",null,null,null], reference: "" },
    { name: "Объём простаты", unit: "см³", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"16",null,null,null], reference: "" },
    { name: "Заключение УЗИ", unit: "", values: [null,"Конкременты не выявлены; в синусе левой почки мелкие гиперэхогенные включения до 3 мм (? микролиты / поствоспалительные изменения)",null,null,null,null,"УЗ-признаки нефроптоза справа; ЧЛК не расширена, конкременты достоверно не лоцированы; область надпочечников без особенностей",null,null,null,null,null,null,null,"Микролитиаз обеих почек, отток мочи не нарушен",null,null,null], reference: "" },
    { name: "Заключение УЗИ мочевого пузыря", unit: "", values: [null,"Патологических изменений не выявлено",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "Патологических изменений не выявлено" },
  ] },
  { name: "ПЦР отделяемого уретры", items: [
    { name: "ДНК Ureaplasma urealyticum", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Ureaplasma parvum", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Trichomonas vaginalis", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Treponema pallidum", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Neisseria gonorrhoeae", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Mycoplasma hominis", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Mycoplasma genitalium", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Gardnerella vaginalis", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Chlamydia trachomatis", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК Candida albicans", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
    { name: "ДНК ВПГ (вирус простого герпеса)", unit: "", values: [null,null,null,null,null,null,null,null,"Не обнаружено",null,null,null,null,null,null,null,null,null], reference: "Не обнаружено" },
  ] },
  { name: "Посев эякулята и чувствительность к антибиотикам", items: [
    { name: "Результат посева", unit: "КОЕ/мл", values: [null,null,null,null,null,null,null,null,null,null,"Рост Corynebacterium 10^2",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Доксициклин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Устойчив",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Азитромицин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Устойчив",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Ципрофлоксацин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Устойчив",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Цефиксим", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Устойчив",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Амоксиклав", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Левофлоксацин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Устойчив",null,null,null,null,null,null,null], reference: "" },
  ] },
  { name: "Общий анализ крови", items: [
    { name: "Лейкоциты (WBC)", unit: "10^9/л", values: ["4.1",null,null,null,null,"3.9",null,"8",null,null,null,"5.3",null,null,"4.64",null,null,null], reference: "4.0-9.0" },
    { name: "Эритроциты (RBC)", unit: "10^12/л", values: ["4.96",null,null,null,null,"4.85",null,"4.44",null,null,null,"4.92",null,null,"5.22",null,null,null], reference: "4.0-5.0" },
    { name: "Гемоглобин (HGB)", unit: "г/л", values: ["156",null,null,null,null,"152",null,"139",null,null,null,"152",null,null,"156",null,null,null], reference: "130-170" },
    { name: "Гематокрит (HCT)", unit: "%", values: ["45.1",null,null,null,null,"42.5",null,"39.5",null,null,null,"43.5",null,null,"48.4",null,null,null], reference: "40-48" },
    { name: "Тромбоциты (PLT)", unit: "10^9/л", values: ["194",null,null,null,null,"194",null,"209",null,null,null,"222",null,null,"218",null,null,null], reference: "120-380" },
    { name: "Средний объём эритроцита (MCV)", unit: "фл", values: ["90.9",null,null,null,null,"87.6",null,"89",null,null,null,"88.4",null,null,"92.7",null,null,null], reference: "80-100" },
    { name: "MCH", unit: "пг", values: ["31.5",null,null,null,null,"31.3",null,"31.3",null,null,null,"30.9",null,null,"29.9",null,null,null], reference: "28-36" },
    { name: "MCHC", unit: "г/л", values: ["346",null,null,null,null,"358",null,"352",null,null,null,"349",null,null,"322",null,null,null], reference: "320-360" },
    { name: "RDW-CV", unit: "%", values: ["11.6",null,null,null,null,"11",null,"12.4",null,null,null,"12.7",null,null,"12.8",null,null,null], reference: "11.5-14.5" },
    { name: "Тромбокрит (PCT)", unit: "%", values: ["0.15",null,null,null,null,"0.14",null,"0.13",null,null,null,"0.13",null,null,"0.203",null,null,null], reference: "03.01.2021, 01.08.2022: 0.1-1.0\n05.01.2026: 0.1-0.36" },
    { name: "MPV", unit: "фл", values: ["7.6",null,null,null,null,"7.1",null,"6.2",null,null,null,"5.8",null,null,"9.3",null,null,null], reference: "03.01.2021, 01.08.2022: 5-10\n05.01.2026: 6-12" },
    { name: "PDW", unit: "%", values: ["17.3",null,null,null,null,"16.3",null,"16.7",null,null,null,"15.9",null,null,"16.1",null,null,null], reference: "10-20" },
    { name: "Палочкоядерные нейтрофилы", unit: "%", values: ["2",null,null,null,null,"0",null,"0.9",null,null,null,"0.5",null,null,null,null,null,null], reference: "0-7" },
    { name: "Сегментоядерные нейтрофилы", unit: "%", values: ["48.9",null,null,null,null,"43",null,"72.6",null,null,null,"52.4",null,null,null,null,null,null], reference: "47-72" },
    { name: "Эозинофилы", unit: "%", values: ["2.4",null,null,null,null,"4.2",null,"3.8",null,null,null,"3.2",null,null,"1.6",null,null,null], reference: "0.5-5" },
    { name: "Базофилы", unit: "%", values: ["1.6",null,null,null,null,"0.9",null,"0.5",null,null,null,"0.9",null,null,"0.4",null,null,null], reference: "0-2" },
    { name: "Моноциты", unit: "%", values: ["12",null,null,null,null,"11.3",null,"6.6",null,null,null,"7.4",null,null,"7",null,null,null], reference: "03.01.2021, 01.08.2022: 3-11\n05.01.2026: 3-12" },
    { name: "Лимфоциты", unit: "%", values: ["33.1",null,null,null,null,"40.6",null,"15.6",null,null,null,"35.6",null,null,"33.3",null,null,null], reference: "19-37" },
    { name: "Нейтрофилы, абсолютное число", unit: "10^9/л", values: ["2.1",null,null,null,null,"1.7",null,"6",null,null,null,"2.8",null,null,"2.68",null,null,null], reference: "1.7-7.7" },
    { name: "Лимфоциты, абсолютное число", unit: "10^9/л", values: ["1.4",null,null,null,null,"1.6",null,"1.2",null,null,null,"1.9",null,null,"1.55",null,null,null], reference: "0.4-4.4" },
    { name: "СОЭ по Вестергрену", unit: "мм/ч", values: ["8",null,null,null,null,"14",null,"38",null,null,null,"8",null,null,"3",null,null,null], reference: "2-15" },
    { name: "Нейтрофилы (авто)", unit: "%", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"57.7",null,null,null], reference: "50-70" },
  ] },
  { name: "Биохимический анализ крови", items: [
    { name: "Ферритин", unit: "нг/мл", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"64.3",null,"98.3",null], reference: "20-300" },
    { name: "Креатинин", unit: "мкмоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,"77.21",null,null,"87.8",null,null,null], reference: "71-115" },
    { name: "Мочевина", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,"6.08",null,null,null,null,null,null], reference: "18-60 лет: 2.5-8.3" },
    { name: "Глюкоза плазмы", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"5.08",null,null,null], reference: "3.9-6.1" },
    { name: "Билирубин общий", unit: "мкмоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,"8.32",null,null,"10.93",null,null,null], reference: "3-20.5" },
    { name: "АСТ", unit: "Ед/л", values: [null,null,null,null,null,null,null,null,null,null,null,"33.9",null,null,"30.9",null,null,"28.9"], reference: "2-38" },
    { name: "АЛТ", unit: "Ед/л", values: [null,null,null,null,null,null,null,null,null,null,null,"53.3",null,null,"46.5",null,null,"54"], reference: "0-40" },
  ] },
  { name: "Липидный профиль", items: [
    { name: "Холестерин общий", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"8.15",null,"6.44","6.56"], reference: "3.6-5.0" },
    { name: "Холестерин ЛПНП", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"4.97",null,null,"3.97"], reference: "0-3.0" },
    { name: "Холестерин ЛПВП", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2.31",null,null,"1.42"], reference: "0.9-1.81" },
    { name: "Триглицериды", unit: "ммоль/л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"1.43"], reference: "30-39 лет: 0.55-3.21" },
  ] },
  { name: "Гормоны щитовидной железы", items: [
    { name: "Т4 общий", unit: "мкг/дл", values: [null,null,null,null,null,null,null,null,null,null,null,"4.47",null,null,"4.44",null,null,null], reference: "6.0-12.5" },
    { name: "Т3 общий", unit: "нг/мл", values: [null,null,null,null,null,null,null,null,null,null,null,"1.1",null,null,"1.12",null,"1.03",null], reference: "0.9-2.0" },
    { name: "ТТГ", unit: "мкМЕ/мл", values: [null,null,null,null,null,null,null,null,null,null,null,"2.67",null,null,"1.66",null,"1.03",null], reference: "0.4-4.0" },
    { name: "Т4 свободный", unit: "нг/дл", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"0.781",null], reference: "0.8-1.8" },
  ] },
  { name: "Осмотр / неотложная помощь", items: [
    { name: "Артериальное давление", unit: "мм рт. ст.", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"120/80",null,null,null,null], reference: "" },
    { name: "Пульс при осмотре", unit: "уд/мин", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"70",null,null,null,null], reference: "" },
    { name: "Повод обращения", unit: "", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"Давление в груди 4 дня, паническая атака",null,null,null,null], reference: "" },
  ] },
  { name: "ЭКГ", items: [
    { name: "ЧСС", unit: "уд/мин", values: [null,null,null,null,null,"60",null,null,null,null,null,null,null,"88","64",null,"88",null], reference: "" },
    { name: "P", unit: "мс", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"97","80",null,"80",null], reference: "" },
    { name: "PQ", unit: "мс", values: [null,null,null,null,null,"130",null,null,null,null,null,null,null,"133","140",null,"140",null], reference: "" },
    { name: "QRS", unit: "мс", values: [null,null,null,null,null,"90",null,null,null,null,null,null,null,"109","100",null,"90",null], reference: "" },
    { name: "QT", unit: "мс", values: [null,null,null,null,null,"310",null,null,null,null,null,null,null,"342","360",null,"320",null], reference: "" },
    { name: "QTc (Bazett)", unit: "мс", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"414","370",null,"390",null], reference: "" },
    { name: "Дисперсия QTc", unit: "мс", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"48",null,null,null,null], reference: "" },
    { name: "Ось QRS", unit: "°", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,"48","44",null,"65",null], reference: "" },
    { name: "Средний RR", unit: "мс", values: [null,null,null,null,null,"1000",null,null,null,null,null,null,null,"682","940",null,"680",null], reference: "" },
    { name: "RR min", unit: "мс", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"820",null,"640",null], reference: "" },
    { name: "RR max", unit: "мс", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,"1000",null,"720",null], reference: "" },
    { name: "Заключение ЭКГ", unit: "", values: [null,null,null,null,null,"Синусовый ритм, ЧСС 60; нормальная ЭОС; неполная БПНПГ; переходная зона V3–V4; признаков острой коронарной недостаточности нет",null,null,null,null,null,null,null,null,"Синусовый ритм; нормальная ЭОС; СРРЖ; неполная БПНПГ",null,"Синусовый ритм, ЧСС 88; вертикальная ЭОС; синдром ранней реполяризации желудочков (СРРЖ)",null], reference: "" },
  ] },
  { name: "Копрограмма", items: [
    { name: "Цвет", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Коричневый",null,null,null,"Коричневый",null,null,null], reference: "светло-тёмно-коричневый" },
    { name: "Консистенция", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Оформленный",null,null,null,"Полуоформленный",null,null,null], reference: "Плотный, оформленный" },
    { name: "Слизь", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Отсутствует",null,null,null,"Отсутствует",null,null,null], reference: "Отсутствует" },
    { name: "Кровь", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Отсутствует",null,null,null,"Отсутствует",null,null,null], reference: "Отсутствует" },
    { name: "Мышечные волокна без исчерченности", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"++",null,null,null,"+",null,null,null], reference: "до ++" },
    { name: "Мышечные волокна с исчерченностью", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"++",null,null,null], reference: "до +" },
    { name: "Соединительная ткань", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружена",null,null,null,"Не обнаружена",null,null,null], reference: "Не обнаружена" },
    { name: "Мыла", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"+",null,null,null,"++",null,null,null], reference: "до +" },
    { name: "Жирные кислоты", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "до +" },
    { name: "Нейтральный жир", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружен",null,null,null,"Не обнаружен",null,null,null], reference: "Не обнаружен" },
    { name: "Лейкоциты", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "до 1 в п/зр" },
    { name: "Эритроциты", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "до 1 в п/зр" },
    { name: "Переваримая клетчатка", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружена",null,null,null,"++",null,null,null], reference: "до ++" },
    { name: "Непереваримая клетчатка", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"++",null,null,null,"+",null,null,null], reference: "до +++" },
    { name: "Крахмал внеклеточный", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"+",null,null,null,"+",null,null,null], reference: "до +" },
    { name: "Крахмал внутриклеточный", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружен",null,null,null,"Не обнаружен",null,null,null], reference: "Не обнаружен" },
    { name: "Йодофильная флора", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружена",null,null,null,"Не обнаружена",null,null,null], reference: "до +" },
    { name: "Простейшие", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
    { name: "Яйца гельминтов", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
    { name: "Дрожжевые грибы", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Не обнаружены",null,null,null,"Не обнаружены",null,null,null], reference: "Не обнаружены" },
  ] },
  { name: "Микробиологическое исследование кала", items: [
    { name: "Патогенные энтеробактерии", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"Нет",null,null,null,null,null,null,null], reference: "Нет" },
    { name: "Типичные кишечные палочки", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"2.1×10^7",null,null,null,null,null,null,null], reference: "10^7-10^8" },
    { name: "Кишечные палочки гемолитические", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"Нет",null,null,null,null,null,null,null], reference: "Нет" },
    { name: "Кишечные палочки лактозонегативные", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"<10^5",null,null,null,null,null,null,null], reference: "<10^5" },
    { name: "Энтерококк", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"10^5",null,null,null,null,null,null,null], reference: "10^5-10^8" },
    { name: "Стафилококк золотистый", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"Нет",null,null,null,null,null,null,null], reference: "Нет" },
    { name: "Стафилококки, другие виды", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"≤10^4",null,null,null,null,null,null,null], reference: "≤10^4" },
    { name: "Неферментирующие энтеробактерии", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"≤10^4",null,null,null,null,null,null,null], reference: "≤10^4" },
    { name: "Candida", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"≤10^4",null,null,null,null,null,null,null], reference: "≤10^4" },
    { name: "Клостридии", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"≤10^5",null,null,null,null,null,null,null], reference: "≤10^5" },
    { name: "Бифидобактерии", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"10^10",null,null,null,null,null,null,null], reference: "10^9-10^10" },
    { name: "Молочнокислые палочки", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"10^8",null,null,null,null,null,null,null], reference: "10^7-10^8" },
    { name: "Условно-патогенные энтеробактерии", unit: "КОЕ/г", values: [null,null,null,null,null,null,null,null,null,null,"<10^4",null,null,null,null,null,null,null], reference: "<10^4" },
  ] },
  { name: "Посев из зева и чувствительность к антибиотикам", items: [
    { name: "Результат посева", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Streptococcus pyogenes +++",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Левофлоксацин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Линезолид", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Клиндамицин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Амоксиклав", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Цефуроксим", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
    { name: "Чувствительность: Кларитромицин", unit: "", values: [null,null,null,null,null,null,null,null,null,null,"Чувствителен",null,null,null,null,null,null,null], reference: "" },
  ] },
  { name: "Рентген / флюорография органов грудной клетки", items: [
    { name: "Рентген грудной клетки", unit: "", values: [null,null,null,null,null,"Без патологии",null,null,null,"Патологических изменений органов грудной клетки не выявлено",null,null,null,null,"Без патологии",null,null,null], reference: "" },
  ] },
  { name: "InBody - состав тела", items: [
    { name: "Оценка InBody", unit: "баллов", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"78",null,null], reference: "" },
    { name: "Вес", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"67.3",null,null], reference: "50.9-68.9" },
    { name: "Общая вода", unit: "л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"39.4",null,null], reference: "33.7-41.1" },
    { name: "Внутриклеточная вода", unit: "л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"24.9",null,null], reference: "20.9-25.5" },
    { name: "Внеклеточная вода", unit: "л", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"14.5",null,null], reference: "12.8-15.6" },
    { name: "Протеин", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"10.8",null,null], reference: "9.0-11.0" },
    { name: "Минералы", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"3.34",null,null], reference: "3.11-3.81" },
    { name: "Мягкая безжировая масса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"50.7",null,null], reference: "43.3-52.9" },
    { name: "Безжировая масса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"53.5",null,null], reference: "45.8-56.0" },
    { name: "Скелетная мышечная масса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"30.4",null,null], reference: "" },
    { name: "Жировая масса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"13.8",null,null], reference: "7.2-14.4" },
    { name: "ИМТ", unit: "кг/м²", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"24.7",null,null], reference: "18.5-24.9" },
    { name: "Процент жира", unit: "%", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"20.5",null,null], reference: "" },
    { name: "Талия/бедро", unit: "", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"0.89",null,null], reference: "0.80-0.90" },
    { name: "Уровень висцерального жира", unit: "", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"5",null,null], reference: "1-9" },
    { name: "Минералы костей", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2.77",null,null], reference: "2.56-3.13" },
    { name: "Активная клеточная масса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"35.7",null,null], reference: "29.9-36.5" },
    { name: "Базальный метаболизм", unit: "ккал", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"1526",null,null], reference: "1482-1729" },
    { name: "Рекомендованный приём калорий InBody", unit: "ккал", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2524",null,null], reference: "оценка прибора" },
    { name: "Индекс скелетной мускулатуры", unit: "кг/м²", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"8.1",null,null], reference: "" },
    { name: "Окружность руки", unit: "см", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"31.9",null,null], reference: "" },
    { name: "Окружность руки без жира", unit: "см", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"28.6",null,null], reference: "" },
    { name: "Идеальный вес InBody", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"63",null,null], reference: "" },
    { name: "Контроль веса", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"-4.3",null,null], reference: "" },
    { name: "Контроль жира", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"-4.3",null,null], reference: "" },
    { name: "Контроль мышц", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"0",null,null], reference: "" },
  ] },
  { name: "InBody - сегментарный анализ", items: [
    { name: "Тощая масса: правая рука", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"3.23",null,null], reference: "109.8% нормы" },
    { name: "Тощая масса: левая рука", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"3.05",null,null], reference: "103.5% нормы" },
    { name: "Тощая масса: туловище", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"25",null,null], reference: "106.4% нормы" },
    { name: "Тощая масса: правая нога", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"7.87",null,null], reference: "96.2% нормы" },
    { name: "Тощая масса: левая нога", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"7.87",null,null], reference: "96.2% нормы" },
    { name: "Жир: правая рука", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"0.6",null,null], reference: "117.6% нормы" },
    { name: "Жир: левая рука", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"0.7",null,null], reference: "134.3% нормы" },
    { name: "Жир: туловище", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"7.2",null,null], reference: "191.1% нормы" },
    { name: "Жир: правая нога", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2",null,null], reference: "128.7% нормы" },
    { name: "Жир: левая нога", unit: "кг", values: [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2",null,null], reference: "127.8% нормы" },
  ] },
  { name: "Позвоночник / опорно-двигательная система", items: [
    { name: "Диагноз травматолога-ортопеда", unit: "", values: [null,null,"ДДЗП грудо-поясничного отдела позвоночника с синдромом люмбалгии",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "—" },
    { name: "МРТ пояснично-крестцового отдела — заключение", unit: "", values: [null,null,null,"МР-картина дистрофических изменений пояснично-крестцового отдела (остеохондроз); переходный позвонок с правосторонним люмбосакральным сочленением",null,null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "—" },
    { name: "МРТ: диски L3/4, L4/5, L5/S1", unit: "", values: [null,null,null,"Дорзальные выбухания L3/4, L4/5, L5/S1 до 1–2 мм с незначительной деформацией дурального мешка; позвоночный и корешковые каналы не сужены; дорзальные грыжи и протрузии не выявлены",null,null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "—" },
    { name: "МРТ-скрининг шейного и грудного отделов", unit: "", values: [null,null,null,"Распространённые дегенеративные изменения шейного и грудного отделов; пролабирование диска Th7/8 до 3 мм с деформацией дурального мешка; рекомендовано прицельное МРТ грудного отдела",null,null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "—" },
    { name: "Диагноз невролога", unit: "", values: [null,null,null,null,"Дегенеративно-дистрофические изменения пояснично-крестцового отдела позвоночника, 1–2 ст., вне обострения",null,null,null,null,null,null,null,null,null,null,null,null,null], reference: "—" },
  ] },
  { name: "Психометрический скрининг / HADS", items: [
    { name: "HADS — тревога", unit: "баллов", values: [null,null,null,null,null,null,null,null,null,null,null,null,"15",null,null,null,null,null], reference: "0-7: норма; 8-10: субклинически; 11-21: клинически выражено" },
    { name: "HADS — депрессия", unit: "баллов", values: [null,null,null,null,null,null,null,null,null,null,null,null,"20",null,null,null,null,null], reference: "0-7: норма; 8-10: субклинически; 11-21: клинически выражено" },
    { name: "Заключение специалиста", unit: "", values: [null,null,null,null,null,null,null,null,null,null,null,null,"R45.3 Деморализация и апатия",null,null,null,null,null], reference: "—" },
  ] },
];

export const sourceDocuments = [
  { type: "PDF", subtitle: "Источник архива", title: "Лабораторные результаты", dates: "2021—2026" },
  { type: "XLSX", subtitle: "Импортированная матрица", title: "Полная матрица анализов", dates: "2021—2026" },
] as const;
